### ISSUE TITLE
Panic: reflect: call of reflect.Value.SetUint on int8 Value

### ISSUE THREAD

**Issue by lretq** [tsatke/nbt#3]
Panic happens when trying to unmarshal NBT to struct. It panics probably while setting the int8 value, which represents a Byte in a struct.

Error on console: 
```
panic: reflect: call of reflect.Value.SetUint on int8 Value

goroutine 1 [running]:
reflect.Value.SetUint({0x49f9a0?, 0xc00010e002?, 0x40c265?}, 0x2)
	/usr/lib/go/src/reflect/value.go:2262 +0xef
github.com/tsatke/nbt.unmarshalInto({0x4d3920, 0xc000010300}, {0x49f9a0?, 0xc00010e002?, 0x4d3fe0?})
	/home/vincent/go/pkg/mod/github.com/tsatke/nbt@v0.0.2/unmarshal.go:23 +0x3c6
github.com/tsatke/nbt.unmarshalInto({0x4d39a0, 0xc0000102c0}, {0x4a8380?, 0xc00010e000?, 0x5806f0?})
	/home/vincent/go/pkg/mod/github.com/tsatke/nbt@v0.0.2/unmarshal.go:76 +0xa4e
github.com/tsatke/nbt.unmarshalInto({0x4d3b20, 0xc00006e1b0}, {0x49eae0?, 0xc00000c030?, 0x4d3fe0?})
	/home/vincent/go/pkg/mod/github.com/tsatke/nbt@v0.0.2/unmarshal.go:84 +0xb1b
github.com/tsatke/nbt.unmarshalInto({0x4d39a0, 0xc000010290}, {0x4a4800?, 0xc00000c030?, 0x8?})
	/home/vincent/go/pkg/mod/github.com/tsatke/nbt@v0.0.2/unmarshal.go:76 +0xa4e
github.com/tsatke/nbt.UnmarshalReader({0x4d3758?, 0xc00006e150?}, {0x4d3ca8?, 0x5806f0?}, {0x49d0a0?, 0xc00000c030})
	/home/vincent/go/pkg/mod/github.com/tsatke/nbt@v0.0.2/unmarshal.go:17 +0x1a8
main.main()
	/home/vincent/projects/go/nbt/main.go:52 +0x14a
```
It seems to fail for this:
```go
type i struct {
	Id  int16 `nbt:"id"`
        Count int8 `nbt:"Count"` < - - -
	Tag tag   `nbt:"tag"`
}
```

Do you have any ideas for this?

**Comment by tpdenk** [comment]
According to https://minecraft.fandom.com/wiki/NBT_format , bytes are signed.
Thus, https://github.com/tsatke/nbt/blob/main/unmarshal.go#L22-L23 is incorrect, and would have to call `target.SetInt`, as in https://github.com/tsatke/nbt/blob/main/unmarshal.go#L31-L32 for example.

**Comment by tpdenk** [comment]
Please upgrade to https://github.com/tsatke/nbt/releases/tag/v0.0.3 . You can do that with `go get -u github.com/tsatke/nbt@v0.0.3` followed by a `go mod tidy` for completeness! Thanks for reporting the issue 🙂

**Comment by lretq** [comment]
Thanks!
