### ISSUE TITLE
Panic when there's a non existant field in a struct

### ISSUE THREAD

**Issue by lretq** [tsatke/nbt#4]
So, I got another panic:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x489221]

goroutine 1 [running]:
github.com/tsatke/nbt.unmarshalInto({0x0, 0x0}, {0x493780?, 0xc00006e168?, 0x4c51c0?})
	/home/vincent/go/pkg/mod/github.com/tsatke/nbt@v0.0.3/unmarshal.go:21 +0x61
github.com/tsatke/nbt.unmarshalInto({0x4c4bd0, 0xc000010290}, {0x498fc0?, 0xc00006e150?, 0x20?})
	/home/vincent/go/pkg/mod/github.com/tsatke/nbt@v0.0.3/unmarshal.go:76 +0xa4e
github.com/tsatke/nbt.UnmarshalReader({0x4c4a48?, 0xc00000e028?}, {0x4c4e90?, 0x56c330?}, {0x490b40?, 0xc00006e150})
	/home/vincent/go/pkg/mod/github.com/tsatke/nbt@v0.0.3/unmarshal.go:17 +0x1a8
main.main()
	/home/vincent/projects/go/nbt/main.go:50 +0xdf
```
This happens when my struct has a field the NBT data doesn't have. I sadly can't guarantee for the nbt data always having every field. 
Is there any way to fix this in my struct or is it something in the library?

**Comment by tpdenk** [comment]
Please upgrade to https://github.com/tsatke/nbt/releases/tag/v0.0.4 . You can do that with `go get -u github.com/tsatke/nbt@v0.0.4` followed by a `go mod tidy` for completeness!
